[openai]
api_key = "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"
model = "gpt-4o-2024-08-06"
#model = "gpt-4-0613"
